security:
    encoders:
        App\Document\User:
           algorithm: bcrypt
    providers:
        webservice:
            id: App\Security\User\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: /home
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/home, roles: ROLE_USER}